dataset:
  train_json_path: ???
  valid_json_path: ???
  test_json_path: ???

tokenizer:
  model_path: ???

log_mel_spectrogram:
  n_fft: 1024
  win_length: 1024
  hop_length: 256
  n_mels: 80
  sample_rate: 22050

model:
  vocab_size: 77
  d_mel: 80
  d_model: 256
  num_heads: 2
  d_ff: 1024
  num_layers: 4
  ff_kernel_size: 9
  adapter_kernel_size: 3
  adapter_dropout_rate: 0.5
  random_slice_size: 64
  dropout_rate: 0.1
  pad_token_id: 0
  lambda_fm: 2.0
  lambda_mel: 45.0
  lambda_align: 2.0
  lambda_var: 1.0

dataloader:
  train:
    batch_size: 16
    shuffle: true
    num_workers: 2
    pin_memory: true
    drop_last: true
  valid:
    batch_size: 16
    shuffle: false
    num_workers: 2
    pin_memory: true
    drop_last: false

train:
  optimizer:
    generator:
      type: adamw
      lr: 2e-4
      beta1: 0.8
      beta2: 0.99
      eps: 1e-9
      weight_decay: 1e-2
    discriminator:
      type: adamw
      lr: 2e-4
      beta1: 0.8
      beta2: 0.99
      eps: 1e-9
      weight_decay: 1e-2
  scheduler:
    generator: # same as HiFi-GAN
      type: epoch_decay
      gamma: 0.999
    discriminator: # same as HiFi-GAN
      type: epoch_decay
      gamma: 0.999
  epochs: 100
  grad_accum_steps: 1
  log_steps: 10
  out_dir: ???
  checkpoint_path:

hydra:
  # https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/
  output_subdir: null
  # https://hydra.cc/docs/configure_hydra/logging/
  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(asctime)s - %(name)s - %(filename)s:%(lineno)d - %(levelname)s: %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      handlers: [console]
    disable_existing_loggers: false
